language: go
go:
  - 1.x
  - tip
os:
  - linux
before_install:
  - go get github.com/golang/lint/golint
  - go get -d ./...
script:
  - go vet ./...
  - export GOFMT=$(gofmt -l .)
  - echo "$GOFMT"
  - $(exit $(echo -n "$GOFMT" | wc -l))
  - export GOLINT=$(golint ./... | grep --invert-match -P "(_string.go:)")
  - echo "$GOLINT"
  - $(exit $(echo -n "$GOLINT" | wc -l))
  - go test -v ./...